### ISSUE TITLE
Issues with cca in both python 2.x and 3.x.

### ISSUE THREAD

**Issue by jason-tilley** [Auerilas/ecopy#14]
I just installed ecopy and was working through the example provided at ReadTheDocs....

```
import ecopy as ep

varespec = ep.load_data('varespec')
varechem = ep.load_data('varechem')

cca_fit = ep.cca(varespec, varechem)
```

However, I end up with an IndexError...

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ecopy/matrix_comp/cca.py", line 144, in __init__
    self.U = self.U[:,self.evals>tolerance]
IndexError: boolean index did not match indexed array along dimension 1; dimension is 44 but corresponding boolean dimension is 14
```

Any idea on what I'm doing wrong?

**Comment by jason-tilley** [comment]
It appears the offending line is:

`self.U = self.U[:,self.evals>tolerance`

**Comment by maurobio** [comment]
This problem is caused by Numpy versions higher than 1.12. From 1.13 arrays of different sizes can no longer be used in boolean comparisions. See here: [https://stackoverflow.com/questions/45207650/indexerror-boolean-index-did-not-match-indexed-array-along-dimension-0](https://stackoverflow.com/questions/45207650/indexerror-boolean-index-did-not-match-indexed-array-along-dimension-0).

**Comment by Auerilas** [comment]
@ForTozs are you still having this issue? I'm just back to getting going on this. I believe @maurobio fixed the problem, as it seems to work for me now.

**Comment by maurobio** [comment]
I confirm this issue has been fixed. cca() now works fine with all versions
of NumPy in both Python 2.x and 3.x.

Em Sex, 5 de abr de 2019 13:06, Auerilas <notifications@github.com>
escreveu:
